services:
  db:
    image: postgres:15
    container_name: tfm-app-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tfmdb
